Mission4_tb454/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_tb454.Models
{
    public class GradeCalcModel
    {
        [Range(1,100)] // Data validation -- make sure number input is between 1 and 100
        public double Assignment { get; set; }
        [Range(1, 100)]
        public double Group_Project { get; set; }
        [Range(1, 100)]
        public double Quiz { get; set; }
        [Range(1, 100)]
        public double Midterm { get; set; }
        [Range(1, 100)]
        public double Final_Exam { get; set; }
        [Range(1, 100)]
        public double Intex { get; set; }
    }
}

Mission4_tb454/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4_tb454.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_tb454.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GradeCalcModel model)
        {
            return View();
        }
    }
}

Mission4_tb454/Views/Blah/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@model GradeCalcModel;

<!--Grade Calculator-->
<h3>Grade Calculator</h3>
<div>Type your score for each category below as a percent (i.e. 50 -- DO NOT USE % SIGN): </div>
<form method="post">
    <label>Assignments: </label>
    <input id="assignmentScore" asp-for="Assignment" /><br />

    <label>Group Projects: </label>
    <input id="groupProjScore" asp-for="Group_Project" /><br />

    <label>Quizzes: </label>
    <input id="quizScore" asp-for="Quiz" /><br />

    <label>Midterm Exam: </label>
    <input id="midtermScore" asp-for="Midterm" /><br />

    <label>Final Exam: </label>
    <input id="finalExamScore" asp-for="Final_Exam" /><br />

    <label>INTEX: </label>
    <input id="intexScore" asp-for="Intex" /><br />

    <input id="calculateBtn" type="submit" value="Calculate Grade" />

    <!--Display error messages per data validation parameters-->
    <div asp-validation-summary="All"></div>

</form>


<br />
<p class="finalGradeP">Final Grade: <span class="finalGradeSpan"></span></p>


<script src="js/gradeCalculator.js"></script>

Mission4_tb454/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Ty's Website";

}

<h1>Ty's Website</h1>
<img src="img/IMG_2856.JPG" class="bigImage" />
<p class="paragraph1">
    I hope to get a lot out of IS 413. I know there is much to learn about C#, ASP.NET, and more. I hope to learn how to create a functioning webapp with this class.
    I'm going to be honest: I don't really like web development, so I hope that I can enjoy this class despite that.
</p>

<br />
<h3>Top 3 Jobs:</h3>

<ol>
    <li>Cybersecurity Consultant</li>
    <li>Database Manager</li>
    <li>Software Developer</li>
</ol>

Mission4_tb454/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="img/IMG_2856.JPG" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/mystyles.css" rel="stylesheet" />
</head>

<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>

</body>

</html>